version: "3"
services:

  opsdroid:
    container_name: opsdroid
    image: opsdroid/opsdroid:latest
    volumes:
      - "./config/:/etc/opsdroid:ro"
      - "./modules/:/root/.opsdroid/modules/opsdroid-modules/skill"
    ports:
    - "8080:8080"

  jenkins:
    container_name: jenkins
    image: jenkins:latest
    volumes:
      - "./jenkins/:/var/jenkins_home"
    ports:
      - "8081:8080"
    restart: "always"