version: "3"
services:

# http://localhost:8081/job/test/buildWithParameters?token=jenkins&param1=test

  opsdroid:
    container_name: opsdroid
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
#    links:
#    - jenkins:jenkins
#
#  jenkins:
#    container_name: jenkins
#    image: jenkins:latest
#    volumes:
#      - "./jenkins/:/var/jenkins_home"
#    expose:
#      - "8081"
#    ports:
#      - "8081:8080"
#    restart: "always"
#
#  mail:
#    container_name: mail
#    image: namshi/smtp
#    ports:
#      - '10025:25'

