services:
    jenkins:
        container_name: jenkins
        expose:
        - '8081'
        image: jenkins:latest
        ports:
        - 8081:8080
        restart: always
        volumes:
        - ~/.jenkins_home/:/var/jenkins_home
    mail:
        container_name: mail
        image: namshi/smtp
        ports:
        - '10025:25'
    opsdroid:
        container_name: opsdroid
        image: opsdroid/opsdroid:dev
        links:
        - jenkins:jenkins
        ports:
        - 8080:8080
        volumes:
        - ./config/:/etc/opsdroid
version: '3'
