##                      _           _     _
##   ___  _ __  ___  __| |_ __ ___ (_) __| |
##  / _ \| '_ \/ __|/ _` | '__/ _ \| |/ _` |
## | (_) | |_) \__ \ (_| | | | (_) | | (_| |
##  \___/| .__/|___/\__,_|_|  \___/|_|\__,_|
##       |_|
##                   __ _
##   ___ ___  _ __  / _(_) __ _
##  / __/ _ \| '_ \| |_| |/ _` |
## | (_| (_) | | | |  _| | (_| |
##  \___\___/|_| |_|_| |_|\__, |
##                        |___/
##

## Host needs to be open to allow access outside of the docker container
web:
  host: "0.0.0.0"
  port: 8080
logging:
  level: debug
  path: /var/log/opsdroid
parsers:
  - name: regex
    enabled: true
connectors:
  - name: websocket
skills:
  - name: opsdroid-jenkins
    path: modules/opsdroid-jenkins
    language: !include language.yaml
    credentials: !include jenkins_credentials.yaml
    jenkins_url: 'http://jenkins:8080'

