web:
  host: "0.0.0.0"
  port: 8080
logging:
  level: debug
  path: /var/log/opsdroid
parsers:
  - name: regex
    enabled: true
connectors:
  - name: websocket
skills:
  - name: opsdroid-jenkins
    path: modules/opsdroid-jenkins
    credentials: !include jenkins_credentials.yamls
    jenkins_url: 'http://jenkins:8080'
